apiVersion: v1
kind: ServiceAccount
metadata:
  name: lazykube
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: config-watcher
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: config-watcher-binding
    namespace: kube-system
roleRef:
    kind: Role
    name: config-watcher
    apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: lazykube
    namespace: kube-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lazykube-config
  namespace: kube-system
data: 
  config: |
    replaceStrategies:
      - case: "quay.io"
        mode: prefix
        value: "quay.azk8s.cn"
      - case: "gcr.io"
        mode: prefix
        value: "gcr.azk8s.cn"
      - case: "k8s.gcr.io"
        mode: prefix
        value: "gcr.azk8s.cn/google-containers"
      - case: "docker.io"
        mode: prefix
        value: "dockerhub.azk8s.cn"
      - case: "default"
        mode: default
        value: "dockerhub.azk8s.cn"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lazykube
  namespace: kube-system
  labels:
    app: lazykube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lazykube
  template:
    metadata:
      labels:
        app: lazykube
    spec:
      serviceAccountName: lazykube
      containers:
        - name: lazykube
          image: joyme/lazykube:dev
          imagePullPolicy: IfNotPresent
          args:
            - -tlsCertFile=/etc/webhook/certs/cert.pem
            - -tlsKeyFile=/etc/webhook/certs/key.pem
            - 2>&1
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
          resources:
              limits:
                cpu: "1"
                memory: "200Mi"
              requests:
                cpu: "0.5"
                memory: "100Mi"
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: webhook-certs
          secret:
            secretName: lazykube-webhook-certs
      
---
apiVersion: v1
kind: Service
metadata:
  name: lazykube-webhook-svc
  namespace: kube-system
  labels:
    app: lazykube
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: lazykube
